#!/usr/bin/env python3
"""
Question seeding script for DTM Test Bot
Har bir fanda minimum 30 ta savol — jami 300 ta
"""

from database.db import Session, init_db
from database.models import Question, Subject
import random


QUESTIONS_DATA = {
    1: [  # Matematika — 30 ta
        {"text_uz": "2 + 2 nechaga teng?", "option_a": "3", "option_b": "4", "option_c": "5", "option_d": "6", "correct_answer": "B"},
        {"text_uz": "Kvadratning perimetri P=16 sm. Tomoni a=?", "option_a": "2 sm", "option_b": "4 sm", "option_c": "8 sm", "option_d": "16 sm", "correct_answer": "B"},
        {"text_uz": "x² - 4x + 4 = 0 tenglamaning ildizi?", "option_a": "x=1", "option_b": "x=-2", "option_c": "x=2", "option_d": "x=4", "correct_answer": "C"},
        {"text_uz": "3² + 4² = ?", "option_a": "25", "option_b": "49", "option_c": "14", "option_d": "7", "correct_answer": "A"},
        {"text_uz": "log₁₀(100) = ?", "option_a": "1", "option_b": "2", "option_c": "10", "option_d": "20", "correct_answer": "B"},
        {"text_uz": "sin(90°) = ?", "option_a": "0", "option_b": "0.5", "option_c": "1", "option_d": "-1", "correct_answer": "C"},
        {"text_uz": "cos(0°) = ?", "option_a": "0", "option_b": "1", "option_c": "-1", "option_d": "0.5", "correct_answer": "B"},
        {"text_uz": "15! / 14! = ?", "option_a": "1", "option_b": "14", "option_c": "15", "option_d": "16", "correct_answer": "C"},
        {"text_uz": "Doira yuzi S = ? (r=5)", "option_a": "10π", "option_b": "25π", "option_c": "5π", "option_d": "50π", "correct_answer": "B"},
        {"text_uz": "√144 = ?", "option_a": "11", "option_b": "12", "option_c": "13", "option_d": "14", "correct_answer": "B"},
        {"text_uz": "2^10 = ?", "option_a": "512", "option_b": "1000", "option_c": "1024", "option_d": "2048", "correct_answer": "C"},
        {"text_uz": "5! = ?", "option_a": "60", "option_b": "100", "option_c": "120", "option_d": "125", "correct_answer": "C"},
        {"text_uz": "Agar a=3, b=4 bo'lsa, a²+b²=?", "option_a": "7", "option_b": "14", "option_c": "25", "option_d": "49", "correct_answer": "C"},
        {"text_uz": "Arifmetik progressiyada a₁=2, d=3 bo'lsa, a₅=?", "option_a": "10", "option_b": "12", "option_c": "14", "option_d": "17", "correct_answer": "C"},
        {"text_uz": "tan(45°) = ?", "option_a": "0", "option_b": "0.5", "option_c": "1", "option_d": "√2", "correct_answer": "C"},
        {"text_uz": "Uchburchak tomonlari 3, 4, 5. Bu qanday uchburchak?", "option_a": "O'tkir", "option_b": "To'g'ri", "option_c": "O'tmas", "option_d": "Teng yonli", "correct_answer": "B"},
        {"text_uz": "(-3)² = ?", "option_a": "-9", "option_b": "-6", "option_c": "6", "option_d": "9", "correct_answer": "D"},
        {"text_uz": "0.1 + 0.2 = ?", "option_a": "0.12", "option_b": "0.3", "option_c": "0.21", "option_d": "0.02", "correct_answer": "B"},
        {"text_uz": "Ikki natural son EKUB(12,18)=?", "option_a": "2", "option_b": "3", "option_c": "6", "option_d": "36", "correct_answer": "C"},
        {"text_uz": "EKUK(4,6)=?", "option_a": "2", "option_b": "12", "option_c": "24", "option_d": "6", "correct_answer": "B"},
        {"text_uz": "Parallelogrammning yuzi S=? (a=6, h=4)", "option_a": "10", "option_b": "20", "option_c": "24", "option_d": "48", "correct_answer": "C"},
        {"text_uz": "Geometrik progressiya: 2, 6, 18... 4-had=?", "option_a": "36", "option_b": "54", "option_c": "72", "option_d": "108", "correct_answer": "B"},
        {"text_uz": "Agar x+y=10, x-y=4 bo'lsa, x=?", "option_a": "3", "option_b": "5", "option_c": "7", "option_d": "9", "correct_answer": "C"},
        {"text_uz": "1/2 + 1/3 = ?", "option_a": "2/5", "option_b": "1/6", "option_c": "5/6", "option_d": "2/6", "correct_answer": "C"},
        {"text_uz": "Silindr hajmi V=? (r=3, h=5)", "option_a": "15π", "option_b": "30π", "option_c": "45π", "option_d": "90π", "correct_answer": "C"},
        {"text_uz": "Binomial koeffitsient C(5,2)=?", "option_a": "5", "option_b": "10", "option_c": "15", "option_d": "20", "correct_answer": "B"},
        {"text_uz": "lg(1000)=?", "option_a": "2", "option_b": "3", "option_c": "4", "option_d": "10", "correct_answer": "B"},
        {"text_uz": "Agar f(x)=2x+1 bo'lsa, f(3)=?", "option_a": "5", "option_b": "6", "option_c": "7", "option_d": "8", "correct_answer": "C"},
        {"text_uz": "sin²x + cos²x = ?", "option_a": "0", "option_b": "1", "option_c": "2", "option_d": "sin(2x)", "correct_answer": "B"},
        {"text_uz": "Kvadrat tenglamada diskriminant D=b²-4ac. a=1,b=2,c=1 bo'lsa D=?", "option_a": "-4", "option_b": "0", "option_c": "4", "option_d": "8", "correct_answer": "B"},
    ],

    2: [  # Fizika — 30 ta
        {"text_uz": "Yerning tortishish kuchi qanday kuch?", "option_a": "Mexanik", "option_b": "Elektromagnit", "option_c": "Gravitatsiya", "option_d": "Yadro", "correct_answer": "C"},
        {"text_uz": "Erkin tushish tezlanishi g=?", "option_a": "8.9 m/s²", "option_b": "9.8 m/s²", "option_c": "10.8 m/s²", "option_d": "11 m/s²", "correct_answer": "B"},
        {"text_uz": "Kuch birligi SI da?", "option_a": "Joule", "option_b": "Vatt", "option_c": "N (Newton)", "option_d": "Pascal", "correct_answer": "C"},
        {"text_uz": "Ishning formulasi W=?", "option_a": "m·a", "option_b": "F·v", "option_c": "F·s·cosα", "option_d": "m·v²", "correct_answer": "C"},
        {"text_uz": "Yorug'lik tezligi vakuumda?", "option_a": "3·10⁶ m/s", "option_b": "3·10⁸ m/s", "option_c": "3·10¹⁰ m/s", "option_d": "3·10⁴ m/s", "correct_answer": "B"},
        {"text_uz": "Kinetik energiya formulasi?", "option_a": "mgh", "option_b": "mv", "option_c": "mv²/2", "option_d": "ma", "correct_answer": "C"},
        {"text_uz": "Potensial energiya formulasi (yerdan balandlikda)?", "option_a": "mv²/2", "option_b": "mgh", "option_c": "Fs", "option_d": "ma²", "correct_answer": "B"},
        {"text_uz": "Ohm qonuni: I=?", "option_a": "U·R", "option_b": "U/R", "option_c": "R/U", "option_d": "U+R", "correct_answer": "B"},
        {"text_uz": "Elektr quvvati birligi?", "option_a": "Amper", "option_b": "Volt", "option_c": "Vatt", "option_d": "Om", "correct_answer": "C"},
        {"text_uz": "Issiqlik miqdori Q=?", "option_a": "mc·ΔT", "option_b": "mv·ΔT", "option_c": "mg·h", "option_d": "F·s", "correct_answer": "A"},
        {"text_uz": "Tovush tezligi havoda taxminan?", "option_a": "34 m/s", "option_b": "340 m/s", "option_c": "3400 m/s", "option_d": "34000 m/s", "correct_answer": "B"},
        {"text_uz": "Nyutonning 2-qonuni: F=?", "option_a": "m/a", "option_b": "m+a", "option_c": "m·a", "option_d": "m·v", "correct_answer": "C"},
        {"text_uz": "Bosim formulasi P=?", "option_a": "F·S", "option_b": "F/S", "option_c": "S/F", "option_d": "F+S", "correct_answer": "B"},
        {"text_uz": "Arximed kuchi nimaga teng?", "option_a": "Suyuqlik og'irligiga", "option_b": "Siqib chiqarilgan suyuqlik og'irligiga", "option_c": "Jism og'irligiga", "option_d": "Jism massasiga", "correct_answer": "B"},
        {"text_uz": "Elektr zaryad birligi SI da?", "option_a": "Volt", "option_b": "Amper", "option_c": "Kulon", "option_d": "Farad", "correct_answer": "C"},
        {"text_uz": "Absolyut nol temperatura?", "option_a": "-100°C", "option_b": "-200°C", "option_c": "-273°C", "option_d": "-373°C", "correct_answer": "C"},
        {"text_uz": "Impuls formulasi p=?", "option_a": "m/v", "option_b": "m·v", "option_c": "m·a", "option_d": "F·t", "correct_answer": "B"},
        {"text_uz": "Qaysi hodisa yadro reaksiyasiga misol?", "option_a": "Yorug'lik sinishi", "option_b": "Elektroliz", "option_c": "Radioaktivlik", "option_d": "Magnit induksiyasi", "correct_answer": "C"},
        {"text_uz": "Mayatnikning tebranish davri T=?", "option_a": "2π√(l/g)", "option_b": "2π√(g/l)", "option_c": "π√(l/g)", "option_d": "2l/g", "correct_answer": "A"},
        {"text_uz": "Elektromagnit to'lqin nima tarqatadi?", "option_a": "Faqat elektr maydon", "option_b": "Faqat magnit maydon", "option_c": "Elektr va magnit maydon", "option_d": "Zarrachalar oqimi", "correct_answer": "C"},
        {"text_uz": "Diffraktsiya nima?", "option_a": "To'lqinning sinishi", "option_b": "To'lqinning to'siqlar atrofida egilishi", "option_c": "To'lqinning qaytishi", "option_d": "To'lqinning kuchayishi", "correct_answer": "B"},
        {"text_uz": "Faradey induksiya qonuni nimani ifodalaydi?", "option_a": "Tok kuchini", "option_b": "EMK ni", "option_c": "Zaryad miqdorini", "option_d": "Quvvatni", "correct_answer": "B"},
        {"text_uz": "Foton energiyasi E=?", "option_a": "hν", "option_b": "mc²", "option_c": "mv²/2", "option_d": "hλ", "correct_answer": "A"},
        {"text_uz": "Gaz bosimi qonuni (T=const): P₁V₁=?", "option_a": "P₂+V₂", "option_b": "P₂V₂", "option_c": "P₂/V₂", "option_d": "P₂·T₂", "correct_answer": "B"},
        {"text_uz": "Elektr sig'im birligi?", "option_a": "Genri", "option_b": "Veber", "option_c": "Farad", "option_d": "Tesia", "correct_answer": "C"},
        {"text_uz": "Mexanik to'lqin tarqalishi uchun nima kerak?", "option_a": "Vakuum", "option_b": "Modda (muhit)", "option_c": "Magnit maydon", "option_d": "Yorug'lik", "correct_answer": "B"},
        {"text_uz": "Nyutonning 3-qonuni nimani ta'riflaydi?", "option_a": "Inersiya", "option_b": "Tezlanish", "option_c": "Ta'sir va aks ta'sir", "option_d": "Tortishish", "correct_answer": "C"},
        {"text_uz": "Massa birligi SI da?", "option_a": "Gramm", "option_b": "Kilogramm", "option_c": "Tonna", "option_d": "Milligramm", "correct_answer": "B"},
        {"text_uz": "Termodinamika 1-qonuni nimani ifodalaydi?", "option_a": "Entropiya ortishi", "option_b": "Energiya saqlanishi", "option_c": "Absolyut nol", "option_d": "Issiqlik o'tkazuvchanlik", "correct_answer": "B"},
        {"text_uz": "Nurlanish qaysi jism xarakteristikasi?", "option_a": "Faqat gaz", "option_b": "Faqat qattiq jism", "option_c": "Barcha isitilgan jismlar", "option_d": "Faqat suyuqlik", "correct_answer": "C"},
    ],

    3: [  # Kimyo — 30 ta
        {"text_uz": "Suvning kimyoviy formulasi?", "option_a": "H2", "option_b": "O2", "option_c": "H2O", "option_d": "CO2", "correct_answer": "C"},
        {"text_uz": "pH=7 bo'lgan eritma qanday?", "option_a": "Kislotali", "option_b": "Asosli", "option_c": "Neytral", "option_d": "Tuzli", "correct_answer": "C"},
        {"text_uz": "Natriy elementi belgisi?", "option_a": "K", "option_b": "Na", "option_c": "N", "option_d": "Ni", "correct_answer": "B"},
        {"text_uz": "NaCl nima?", "option_a": "Osh tuzi", "option_b": "Soda", "option_c": "Ohak", "option_d": "Mis sulfat", "correct_answer": "A"},
        {"text_uz": "Davriy sistemani kim yaratgan?", "option_a": "Lavuazye", "option_b": "Darvin", "option_c": "Mendeleyev", "option_d": "Nyuton", "correct_answer": "C"},
        {"text_uz": "H₂SO₄ qanday kislota?", "option_a": "Xlorid", "option_b": "Sulfat", "option_c": "Azot", "option_d": "Karbonat", "correct_answer": "B"},
        {"text_uz": "O₂ qanday modda?", "option_a": "Birikmа", "option_b": "Aralashma", "option_c": "Oddiy modda", "option_d": "Tuz", "correct_answer": "C"},
        {"text_uz": "Elektrolitik dissotsilanishda NaOH nima hosil qiladi?", "option_a": "H⁺ ionlari", "option_b": "Na⁺ va OH⁻ ionlari", "option_c": "O²⁻ ionlari", "option_d": "Na va O", "correct_answer": "B"},
        {"text_uz": "Organik kimyoning asosi qaysi element?", "option_a": "Azot", "option_b": "Kislorod", "option_c": "Uglerod", "option_d": "Vodorod", "correct_answer": "C"},
        {"text_uz": "Metan formulasi?", "option_a": "C₂H₆", "option_b": "CH₄", "option_c": "C₃H₈", "option_d": "C₂H₄", "correct_answer": "B"},
        {"text_uz": "Oksidlanish jarayonida elektron?", "option_a": "Qo'shiladi", "option_b": "Yo'qoladi", "option_c": "O'zgarmaydi", "option_d": "Ko'payadi", "correct_answer": "B"},
        {"text_uz": "Qaytarilish jarayonida elektron?", "option_a": "Yo'qoladi", "option_b": "Qo'shiladi", "option_c": "O'zgarmaydi", "option_d": "Kamayadi", "correct_answer": "B"},
        {"text_uz": "Ca(OH)₂ nima deyiladi?", "option_a": "Ohak suvi", "option_b": "Soda", "option_c": "Mis vitriol", "option_d": "Kaliy permanganat", "correct_answer": "A"},
        {"text_uz": "Vodorod atomi nechta proton tutadi?", "option_a": "0", "option_b": "1", "option_c": "2", "option_d": "3", "correct_answer": "B"},
        {"text_uz": "Mis elementining belgisi?", "option_a": "Co", "option_b": "Cr", "option_c": "Cu", "option_d": "Ca", "correct_answer": "C"},
        {"text_uz": "CO₂ qanday oksid?", "option_a": "Asosli", "option_b": "Kislotali", "option_c": "Amfoter", "option_d": "Neytral", "correct_answer": "B"},
        {"text_uz": "Etanol formulasi?", "option_a": "CH₃OH", "option_b": "C₂H₅OH", "option_c": "C₃H₇OH", "option_d": "C₄H₉OH", "correct_answer": "B"},
        {"text_uz": "Benzol formulasi?", "option_a": "C₅H₁₀", "option_b": "C₆H₁₂", "option_c": "C₆H₆", "option_d": "C₄H₈", "correct_answer": "C"},
        {"text_uz": "Mol nima?", "option_a": "Massa birligi", "option_b": "6.02·10²³ ta zarracha miqdori", "option_c": "Hajm birligi", "option_d": "Zichlik birligi", "correct_answer": "B"},
        {"text_uz": "Kumush elementining belgisi?", "option_a": "Si", "option_b": "Sb", "option_c": "Ag", "option_d": "Au", "correct_answer": "C"},
        {"text_uz": "Qaysi reaksiya egzotermik?", "option_a": "Issiqlik yutiladi", "option_b": "Issiqlik ajraladi", "option_c": "Massа o'zgaradi", "option_d": "Rang o'zgaradi", "correct_answer": "B"},
        {"text_uz": "Uglerod qancha valentli bo'lishi mumkin?", "option_a": "Faqat 2", "option_b": "Faqat 4", "option_c": "2 yoki 4", "option_d": "1, 2, 3 yoki 4", "correct_answer": "C"},
        {"text_uz": "Alkangоlarning umumiy formulasi?", "option_a": "CₙH₂ₙ", "option_b": "CₙH₂ₙ₊₂", "option_c": "CₙH₂ₙ₋₂", "option_d": "CₙHₙ", "correct_answer": "B"},
        {"text_uz": "Alkenlarning umumiy formulasi?", "option_a": "CₙH₂ₙ₊₂", "option_b": "CₙH₂ₙ", "option_c": "CₙH₂ₙ₋₂", "option_d": "CₙHₙ", "correct_answer": "B"},
        {"text_uz": "Kislota va asos reaksiyasi?", "option_a": "Oksidlanish", "option_b": "Neytrallash", "option_c": "Parchalanish", "option_d": "Birikish", "correct_answer": "B"},
        {"text_uz": "Temir elementining belgisi?", "option_a": "Te", "option_b": "Ti", "option_c": "Fe", "option_d": "Fo", "correct_answer": "C"},
        {"text_uz": "Qaysi modda eng kuchli kislota?", "option_a": "CH₃COOH", "option_b": "H₂CO₃", "option_c": "HCl", "option_d": "H₂SO₄", "correct_answer": "D"},
        {"text_uz": "Kremniy elementining belgisi?", "option_a": "Cr", "option_b": "Si", "option_c": "Sn", "option_d": "Sr", "correct_answer": "B"},
        {"text_uz": "Ammoniyak formulasi?", "option_a": "NO₂", "option_b": "N₂O", "option_c": "NH₃", "option_d": "N₂H₄", "correct_answer": "C"},
        {"text_uz": "Elektroliz nima?", "option_a": "Issiqlik ta'sirida parchalanish", "option_b": "Elektr toki ta'sirida parchalanish", "option_c": "Yorug'lik ta'sirida reaksiya", "option_d": "Bosim ostida sintez", "correct_answer": "B"},
    ],

    4: [  # Biologiya — 30 ta
        {"text_uz": "Odamda nechta juft qovurg'a bor?", "option_a": "10", "option_b": "12", "option_c": "14", "option_d": "16", "correct_answer": "B"},
        {"text_uz": "Fotosintez qaysi organoidda bo'ladi?", "option_a": "Yadro", "option_b": "Mitoxondriya", "option_c": "Xloroplast", "option_d": "Lizosoma", "correct_answer": "C"},
        {"text_uz": "DNK nimani kodlaydi?", "option_a": "Yog'larni", "option_b": "Uglevodlarni", "option_c": "Oqsillarni", "option_d": "Vitaminlarni", "correct_answer": "C"},
        {"text_uz": "Odam qon guruhlari nechtа?", "option_a": "2", "option_b": "3", "option_c": "4", "option_d": "5", "correct_answer": "C"},
        {"text_uz": "Miya qaysi organizmda eng rivojlangan?", "option_a": "Baliq", "option_b": "Sut emizuvchilar", "option_c": "Hasharotlar", "option_d": "Sudralib yuruvchilar", "correct_answer": "B"},
        {"text_uz": "ATP nima?", "option_a": "Oqsil", "option_b": "Yog'", "option_c": "Energiya tashuvchi molekula", "option_d": "Ferment", "correct_answer": "C"},
        {"text_uz": "Mitoz necha bosqichdan iborat?", "option_a": "2", "option_b": "3", "option_c": "4", "option_d": "5", "correct_answer": "C"},
        {"text_uz": "Qaysi organoid hujayraning 'energiya stantsiyasi'?", "option_a": "Ribosoma", "option_b": "Lizosoma", "option_c": "Mitoxondriya", "option_d": "Vakuola", "correct_answer": "C"},
        {"text_uz": "Odamda nechta juft xromosoma bor?", "option_a": "21", "option_b": "22", "option_c": "23", "option_d": "24", "correct_answer": "C"},
        {"text_uz": "Qon tarkibiga kirmaydigan element?", "option_a": "Eritrositlar", "option_b": "Leykositlar", "option_c": "Trombositlar", "option_d": "Neyronlar", "correct_answer": "D"},
        {"text_uz": "Fotosintez jarayonida nima hosil bo'ladi?", "option_a": "CO₂ va H₂O", "option_b": "O₂ va glyukoza", "option_c": "N₂ va ATP", "option_d": "H₂ va O₂", "correct_answer": "B"},
        {"text_uz": "Irsiyat qonunlarini kim kashf etgan?", "option_a": "Darvin", "option_b": "Mendel", "option_c": "Lamark", "option_d": "Kox", "correct_answer": "B"},
        {"text_uz": "RNK ning asosiy vazifasi?", "option_a": "Irsiy ma'lumot saqlash", "option_b": "Oqsil sintezi", "option_c": "Energiya olish", "option_d": "Yog' sintezi", "correct_answer": "B"},
        {"text_uz": "Virus tarkibiga nimalar kiradi?", "option_a": "Hujayra va DNK", "option_b": "Faqat oqsil", "option_c": "Nuklein kislota va oqsil qobiq", "option_d": "Hujayra membranasi", "correct_answer": "C"},
        {"text_uz": "Inson yuragida nechta kamera bor?", "option_a": "2", "option_b": "3", "option_c": "4", "option_d": "5", "correct_answer": "C"},
        {"text_uz": "Qaysi ferment kraxmalni parchalaydi?", "option_a": "Pepsin", "option_b": "Lipaza", "option_c": "Amilaza", "option_d": "Tripsin", "correct_answer": "C"},
        {"text_uz": "Neyron nima?", "option_a": "Qon hujayra", "option_b": "Asab hujayra", "option_c": "Muskul hujayra", "option_d": "Suyak hujayra", "correct_answer": "B"},
        {"text_uz": "Siydik qaysi organda hosil bo'ladi?", "option_a": "Jigar", "option_b": "Taloq", "option_c": "Buyrak", "option_d": "O't pufagi", "correct_answer": "C"},
        {"text_uz": "O'simliklarning suv va mineral tuzlarni o'zlashtirishi qayerdan boshlanadi?", "option_a": "Barg", "option_b": "Poya", "option_c": "Ildiz", "option_d": "Gul", "correct_answer": "C"},
        {"text_uz": "Qaysi vitamin kalsiy so'rilishini ta'minlaydi?", "option_a": "A", "option_b": "B", "option_c": "C", "option_d": "D", "correct_answer": "D"},
        {"text_uz": "Meyoz natijasida nechta hujayra hosil bo'ladi?", "option_a": "2", "option_b": "4", "option_c": "8", "option_d": "16", "correct_answer": "B"},
        {"text_uz": "Qon plazmasining asosiy komponenti?", "option_a": "Eritrositlar", "option_b": "Oqsil", "option_c": "Suv", "option_d": "Tuz", "correct_answer": "C"},
        {"text_uz": "Immunitet nima?", "option_a": "Kasallik", "option_b": "Organizmning himoya tizimi", "option_c": "Gormon", "option_d": "Ferment", "correct_answer": "B"},
        {"text_uz": "O'simlik hujayrasida qaysi organoid hayvon hujayrасида yo'q?", "option_a": "Mitoxondriya", "option_b": "Ribosoma", "option_c": "Xloroplast", "option_d": "Yadro", "correct_answer": "C"},
        {"text_uz": "Evolyutsiya nazariyasini kim yaratgan?", "option_a": "Mendel", "option_b": "Darvin", "option_c": "Pastyur", "option_d": "Linney", "correct_answer": "B"},
        {"text_uz": "Nafas olish jarayonida nima iste'mol qilinadi?", "option_a": "CO₂", "option_b": "N₂", "option_c": "O₂", "option_d": "H₂", "correct_answer": "C"},
        {"text_uz": "Ovqat hazm qilish qaysi organadan boshlanadi?", "option_a": "Oshqozon", "option_b": "O'n ikki barmoqli ichak", "option_c": "Og'iz bo'shlig'i", "option_d": "Qizil o'ngach", "correct_answer": "C"},
        {"text_uz": "Qaysi guruh organizmlari prokariot?", "option_a": "O'simliklar", "option_b": "Hayvonlar", "option_c": "Bakteriyalar", "option_d": "Zamburug'lar", "correct_answer": "C"},
        {"text_uz": "Insulin qaysi organ ishlab chiqaradi?", "option_a": "Jigar", "option_b": "Buyrak", "option_c": "Oshqozon osti bezi", "option_d": "Taloq", "correct_answer": "C"},
        {"text_uz": "Ko'zning to'r pardasi qanday hujayra tutadi?", "option_a": "Tayoqcha va kolba", "option_b": "Neyron va glia", "option_c": "Epiteliy va muskul", "option_d": "Pigment va shaffof", "correct_answer": "A"},
    ],

    5: [  # Tarix — 30 ta
        {"text_uz": "O'zbekiston qachon mustaqil bo'ldi?", "option_a": "1990", "option_b": "1991", "option_c": "1992", "option_d": "1993", "correct_answer": "B"},
        {"text_uz": "Amir Temur qaysi yilda vafot etgan?", "option_a": "1404", "option_b": "1405", "option_c": "1406", "option_d": "1407", "correct_answer": "B"},
        {"text_uz": "Samarqand qachon Temur poytaxtiga aylangan?", "option_a": "1370", "option_b": "1380", "option_c": "1390", "option_d": "1400", "correct_answer": "A"},
        {"text_uz": "Birinchi Jahon urushi qachon boshlangan?", "option_a": "1912", "option_b": "1913", "option_c": "1914", "option_d": "1915", "correct_answer": "C"},
        {"text_uz": "Ikkinchi Jahon urushi qachon tugagan?", "option_a": "1944", "option_b": "1945", "option_c": "1946", "option_d": "1947", "correct_answer": "B"},
        {"text_uz": "O'zbekiston Respublikasining birinchi Prezidenti kim?", "option_a": "Sh. Mirziyoyev", "option_b": "I. Karimov", "option_c": "A. Mutalov", "option_d": "R. Nishonov", "correct_answer": "B"},
        {"text_uz": "Buyuk Ipak yo'li qachon shakllangan?", "option_a": "Miloddan avvalgi I asr", "option_b": "Miloddan avvalgi II asr", "option_c": "Milodiy I asr", "option_d": "Milodiy II asr", "correct_answer": "B"},
        {"text_uz": "Al-Xorazmiy kim bo'lgan?", "option_a": "Shoir", "option_b": "Matematik va astronom", "option_c": "Sarkarda", "option_d": "Arxitektor", "correct_answer": "B"},
        {"text_uz": "Ibn Sino qaysi asarda tibbiyotni tizimlashtirgan?", "option_a": "Kitob al-Qonun", "option_b": "Avesto", "option_c": "Temurnoma", "option_d": "Boburnoma", "correct_answer": "A"},
        {"text_uz": "Fransiya inqilobi qachon bo'lgan?", "option_a": "1776", "option_b": "1789", "option_c": "1812", "option_d": "1848", "correct_answer": "B"},
        {"text_uz": "Amerika mustaqillik deklaratsiyasi qachon e'lon qilingan?", "option_a": "1775", "option_b": "1776", "option_c": "1777", "option_d": "1778", "correct_answer": "B"},
        {"text_uz": "Rus inqilobi qachon bo'lgan?", "option_a": "1915", "option_b": "1916", "option_c": "1917", "option_d": "1918", "correct_answer": "C"},
        {"text_uz": "Berlin devori qachon qurilgan?", "option_a": "1959", "option_b": "1961", "option_c": "1963", "option_d": "1965", "correct_answer": "B"},
        {"text_uz": "Berlin devori qachon qulatilgan?", "option_a": "1987", "option_b": "1988", "option_c": "1989", "option_d": "1990", "correct_answer": "C"},
        {"text_uz": "Ulug'bek rasadxonasi qachon qurilgan?", "option_a": "1420s", "option_b": "1450s", "option_c": "1400s", "option_d": "1380s", "correct_answer": "A"},
        {"text_uz": "Qadimgi Rim imperiyasi qachon qulab tushgan?", "option_a": "375", "option_b": "410", "option_c": "476", "option_d": "527", "correct_answer": "C"},
        {"text_uz": "O'rta asr Yevropa tarixi qaysi davrni qamrаb oladi?", "option_a": "V-XV asrlar", "option_b": "I-V asrlar", "option_c": "XV-XVIII asrlar", "option_d": "III-VIII asrlar", "correct_answer": "A"},
        {"text_uz": "Temuriylar sulolasi qaysi yilda barham topgan?", "option_a": "1500", "option_b": "1507", "option_c": "1510", "option_d": "1526", "correct_answer": "B"},
        {"text_uz": "Bobur Hindistonda qaysi sulolaga asos solgan?", "option_a": "Temuriylar", "option_b": "Safaviylar", "option_c": "Boburiylar (Buyuk Mo'g'ullar)", "option_d": "Shayboniylar", "correct_answer": "C"},
        {"text_uz": "Xiva xonligi qachon tashkil topgan?", "option_a": "XVI asr boshi", "option_b": "XV asr oxiri", "option_c": "XVII asr boshi", "option_d": "XVIII asr", "correct_answer": "A"},
        {"text_uz": "Qo'qon xonligi qachon tuzilgan?", "option_a": "XVII asr", "option_b": "XVIII asr boshi", "option_c": "XVIII asr o'rtasi", "option_d": "XIX asr boshi", "correct_answer": "B"},
        {"text_uz": "Rossiya O'rta Osiyoni to'liq bosib olishni qachon yakunlagan?", "option_a": "1868", "option_b": "1876", "option_c": "1885", "option_d": "1895", "correct_answer": "C"},
        {"text_uz": "Jadidchilik harakati O'zbekistonda qachon paydo bo'lgan?", "option_a": "XIX asrning boshi", "option_b": "XIX asrning o'rtasi", "option_c": "XIX asrning oxiri", "option_d": "XX asrning boshi", "correct_answer": "C"},
        {"text_uz": "O'zbekiston SSR qachon tashkil topgan?", "option_a": "1922", "option_b": "1924", "option_c": "1925", "option_d": "1936", "correct_answer": "B"},
        {"text_uz": "Ikkinchi Jahon urushi qachon boshlangan?", "option_a": "1937", "option_b": "1938", "option_c": "1939", "option_d": "1940", "correct_answer": "C"},
        {"text_uz": "BMT qachon tashkil topgan?", "option_a": "1944", "option_b": "1945", "option_c": "1946", "option_d": "1947", "correct_answer": "B"},
        {"text_uz": "Sovuq urush qachon boshlangan?", "option_a": "1944", "option_b": "1945", "option_c": "1947", "option_d": "1950", "correct_answer": "C"},
        {"text_uz": "MDH (Mustaqil Davlatlar Hamdo'stligi) qachon tashkil topgan?", "option_a": "1990", "option_b": "1991", "option_c": "1992", "option_d": "1993", "correct_answer": "B"},
        {"text_uz": "Avesto qaysi xalqning muqaddas kitobi?", "option_a": "Arablar", "option_b": "Turklar", "option_c": "Forslar va zardushtiylar", "option_d": "Hindlar", "correct_answer": "C"},
        {"text_uz": "Ulug'bek kim tomonidan o'ldirilgan?", "option_a": "Ko'chmаnchi bosqinchilar", "option_b": "O'z o'g'li Abdullatif tomonidan", "option_c": "Dushman sarkardasi tomonidan", "option_d": "Saroy fitnachilar", "correct_answer": "B"},
    ],

    6: [  # Ona tili — 30 ta
        {"text_uz": "Qaysi so'z ot hisoblanadi?", "option_a": "Yozmoq", "option_b": "Kitob", "option_c": "Chiroyli", "option_d": "Tez", "correct_answer": "B"},
        {"text_uz": "'Daraxt' so'zi qaysi so'z turkumiga kiradi?", "option_a": "Sifat", "option_b": "Ot", "option_c": "Fe'l", "option_d": "Ravish", "correct_answer": "B"},
        {"text_uz": "Qaysi so'z fe'l hisoblanadi?", "option_a": "Kitob", "option_b": "Chiroyli", "option_c": "Yozmoq", "option_d": "Tez", "correct_answer": "C"},
        {"text_uz": "Ega gapning qaysi bo'lagi?", "option_a": "Ikkinchi darajali", "option_b": "Asosiy (bosh bo'lak)", "option_c": "To'ldiruvchi", "option_d": "Aniqlovchi", "correct_answer": "B"},
        {"text_uz": "Kesim gapning qaysi bo'lagi?", "option_a": "Ikkinchi darajali", "option_b": "Aniqlovchi", "option_c": "Asosiy (bosh bo'lak)", "option_d": "To'ldiruvchi", "correct_answer": "C"},
        {"text_uz": "O'zbek alifbosida nechta harf bor (lotincha)?", "option_a": "26", "option_b": "28", "option_c": "29", "option_d": "32", "correct_answer": "C"},
        {"text_uz": "Qaysi so'z sifat hisoblanadi?", "option_a": "Kitob", "option_b": "Qizil", "option_c": "Yozmoq", "option_d": "Tez yugurdi", "correct_answer": "B"},
        {"text_uz": "Son nima?", "option_a": "Harakat bildiruvchi so'z", "option_b": "Belgi bildiruvchi so'z", "option_c": "Miqdor yoki tartib bildiruvchi so'z", "option_d": "Predmet bildiruvchi so'z", "correct_answer": "C"},
        {"text_uz": "Olmosh nima?", "option_a": "Harakatni bildiradi", "option_b": "Boshqa so'zlarni almashtiradi", "option_c": "Belgini bildiradi", "option_d": "Miqdorni bildiradi", "correct_answer": "B"},
        {"text_uz": "Ravish nima bildiradi?", "option_a": "Predmet", "option_b": "Belgi", "option_c": "Miqdor", "option_d": "Harakat belgisi", "correct_answer": "D"},
        {"text_uz": "Ko'makchi qanday so'z turkumi?", "option_a": "Mustaqil so'z", "option_b": "Yordamchi so'z", "option_c": "Undov so'z", "option_d": "Modal so'z", "correct_answer": "B"},
        {"text_uz": "Bog'lovchi qanday so'z turkumi?", "option_a": "Mustaqil", "option_b": "Undov", "option_c": "Yordamchi", "option_d": "Taqlid", "correct_answer": "C"},
        {"text_uz": "Qo'shma gap degani nima?", "option_a": "Bir ega va bir kesimli gap", "option_b": "Ikki yoki undan ortiq sodda gapdan iborat gap", "option_c": "So'rog'li gap", "option_d": "Buyruq gapi", "correct_answer": "B"},
        {"text_uz": "Undov gap qanday gap?", "option_a": "So'roq bildiruvchi", "option_b": "His-hayajon bildiruvchi", "option_c": "Buyruq bildiruvchi", "option_d": "Xabar bildiruvchi", "correct_answer": "B"},
        {"text_uz": "'Kitoblar' so'zida nechta morfema bor?", "option_a": "1", "option_b": "2", "option_c": "3", "option_d": "4", "correct_answer": "B"},
        {"text_uz": "Affiks nima?", "option_a": "So'z o'zagi", "option_b": "So'z yasovchi yoki o'zgartiruvchi qo'shimcha", "option_c": "So'z boshi", "option_d": "Gap bo'lagi", "correct_answer": "B"},
        {"text_uz": "Antonim so'zlar deganda nima tushuniladi?", "option_a": "Ma'nodosh so'zlar", "option_b": "Qarama-qarshi ma'noli so'zlar", "option_c": "Ko'p ma'noli so'zlar", "option_d": "Shakldosh so'zlar", "correct_answer": "B"},
        {"text_uz": "Sinonim so'zlar deganda nima tushuniladi?", "option_a": "Qarama-qarshi ma'noli so'zlar", "option_b": "Ma'nodosh so'zlar", "option_c": "Shakldosh so'zlar", "option_d": "Ko'p ma'noli so'zlar", "correct_answer": "B"},
        {"text_uz": "Omonim so'zlar deganda nima tushuniladi?", "option_a": "Ma'nodosh so'zlar", "option_b": "Antonim so'zlar", "option_c": "Bir xil yoziladigan lekin ma'nosi turli so'zlar", "option_d": "Ko'p ma'noli so'zlar", "correct_answer": "C"},
        {"text_uz": "To'ldiruvchi gap qaysi savolga javob beradi?", "option_a": "Qanday? Qanaqa?", "option_b": "Kimning? Nimaning?", "option_c": "Kimga? Nimaga? Kimni? Nimani?", "option_d": "Qayer? Qachon?", "correct_answer": "C"},
        {"text_uz": "Aniqlovchi gap qaysi savolga javob beradi?", "option_a": "Kimga? Nimaga?", "option_b": "Qanday? Qanaqa? Qaysi?", "option_c": "Qaerga? Qachon?", "option_d": "Kim? Nima?", "correct_answer": "B"},
        {"text_uz": "Hol gap qaysi savolga javob beradi?", "option_a": "Kim? Nima?", "option_b": "Qanday? Qanaqa?", "option_c": "Qayer? Qachon? Qanday?", "option_d": "Kimning? Nimaning?", "correct_answer": "C"},
        {"text_uz": "Nutq uslublari nechtа?", "option_a": "3", "option_b": "4", "option_c": "5", "option_d": "6", "correct_answer": "C"},
        {"text_uz": "Badiiy uslubning asosiy xususiyati?", "option_a": "Rasmiylik", "option_b": "Ilmiyllik", "option_c": "Ta'sirchanlik va obrazlilik", "option_d": "Soddalik", "correct_answer": "C"},
        {"text_uz": "Ilmiy uslub qayerda ishlatiladi?", "option_a": "Adabiy asarlarda", "option_b": "Ilmiy maqola va kitoblarda", "option_c": "Kundalik muloqotda", "option_d": "Rasmiy hujjatlarda", "correct_answer": "B"},
        {"text_uz": "Frazeologizm nima?", "option_a": "Bitta so'z", "option_b": "Barqaror so'z birikmasi", "option_c": "Gap turi", "option_d": "Qo'shimcha", "correct_answer": "B"},
        {"text_uz": "Metafora nima?", "option_a": "Tashbeh", "option_b": "Ko'chma ma'noli ta'bir", "option_c": "Takror", "option_d": "Mubolag'a", "correct_answer": "B"},
        {"text_uz": "Epitet nima?", "option_a": "Harakat bildiruvchi so'z", "option_b": "Badiiy sifatlash", "option_c": "Qarama-qarshilik", "option_d": "So'z o'yini", "correct_answer": "B"},
        {"text_uz": "O'zbek tilida nechta unli tovush bor?", "option_a": "5", "option_b": "6", "option_c": "7", "option_d": "8", "correct_answer": "B"},
        {"text_uz": "Qaysi so'z undov hisoblanadi?", "option_a": "Lekin", "option_b": "Va", "option_c": "Oh!", "option_d": "Ham", "correct_answer": "C"},
    ],

    7: [  # Adabiyot — 30 ta
        {"text_uz": "Alisher Navoiy qaysi asr shoiri?", "option_a": "14-asr", "option_b": "15-asr", "option_c": "16-asr", "option_d": "17-asr", "correct_answer": "B"},
        {"text_uz": "'Layli va Majnun' dostonini kim yozgan?", "option_a": "Alisher Navoiy", "option_b": "Abdulla Qodiriy", "option_c": "Cho'lpon", "option_d": "Hamza", "correct_answer": "A"},
        {"text_uz": "Navoiy qanday qo'shimcha nom bilan ham tanilgan?", "option_a": "Nizomiy", "option_b": "Husayn Boyqaro", "option_c": "Foniy", "option_d": "Bedil", "correct_answer": "C"},
        {"text_uz": "'O'tkan kunlar' romani muallifi?", "option_a": "Cho'lpon", "option_b": "Hamza", "option_c": "Abdulla Qodiriy", "option_d": "Fitrat", "correct_answer": "C"},
        {"text_uz": "Hamza Hakimzodaning to'liq ismi?", "option_a": "Hamza Hakimzoda Niyoziy", "option_b": "Hamza Sultonov", "option_c": "Hamza Karimov", "option_d": "Hamza Yusupov", "correct_answer": "A"},
        {"text_uz": "'Shum bola' asarini kim yozgan?", "option_a": "Hamza", "option_b": "G'afur G'ulom", "option_c": "Abdulla Qodiriy", "option_d": "Cho'lpon", "correct_answer": "B"},
        {"text_uz": "Cho'lponning asl ismi?", "option_a": "Abdulhamid Sulaymon", "option_b": "Abdulla Hamid", "option_c": "Hamid Sulaymon", "option_d": "Abdulhamid Hamid", "correct_answer": "A"},
        {"text_uz": "Navoiyning 'Xamsa'si nechta dostondan iborat?", "option_a": "3", "option_b": "4", "option_c": "5", "option_d": "6", "correct_answer": "C"},
        {"text_uz": "'Farhod va Shirin' dostonini kim yozgan?", "option_a": "Nizomiy", "option_b": "Navoiy", "option_c": "Fuzuliy", "option_d": "Bedil", "correct_answer": "B"},
        {"text_uz": "Dostondagi qahramonlar sevgisi qaysi asarning mavzusi?", "option_a": "Faqat epik asarlar", "option_b": "Lirik she'rlar", "option_c": "Lirik-epik janr", "option_d": "Dramatik asarlar", "correct_answer": "C"},
        {"text_uz": "G'azal qanday janr?", "option_a": "Epik", "option_b": "Dramatik", "option_c": "Lirik", "option_d": "Lirik-epik", "correct_answer": "C"},
        {"text_uz": "Ruboiy necha misradan iborat?", "option_a": "2", "option_b": "3", "option_c": "4", "option_d": "6", "correct_answer": "C"},
        {"text_uz": "Doston qanday janr?", "option_a": "Lirik", "option_b": "Dramatik", "option_c": "Epik yoki lirik-epik", "option_d": "Satirik", "correct_answer": "C"},
        {"text_uz": "Hajviy asar nima?", "option_a": "Qayg'uli asar", "option_b": "Keskin tanqidiy yoki kulgili asar", "option_c": "Qahramonlik asari", "option_d": "Romantik asar", "correct_answer": "B"},
        {"text_uz": "Abdulla Oripovning eng mashhur she'rlar to'plami?", "option_a": "Qo'shiqlar", "option_b": "Muножот", "option_c": "O'zbegim", "option_d": "Bahor", "correct_answer": "C"},
        {"text_uz": "Erkin Vohidov qaysi janrda mashhur?", "option_a": "Proza", "option_b": "Drama", "option_c": "She'riyat", "option_d": "Publitsistika", "correct_answer": "C"},
        {"text_uz": "Navoiyning ona tili qaysi edi?", "option_a": "Fors tili", "option_b": "Arab tili", "option_c": "Eski o'zbek (chig'atoy) tili", "option_d": "Mo'g'ul tili", "correct_answer": "C"},
        {"text_uz": "'Muqaddimatul adab' asarini kim yozgan?", "option_a": "Navoiy", "option_b": "Zamaxshariy", "option_c": "Beruniy", "option_d": "Ulug'bek", "correct_answer": "B"},
        {"text_uz": "Shahnoma eposi qaysi millat adabiyotiga tegishli?", "option_a": "O'zbek", "option_b": "Arab", "option_c": "Fors-tojik", "option_d": "Turk", "correct_answer": "C"},
        {"text_uz": "'Alpomish' — qaysi xalqning eposi?", "option_a": "Qozoq", "option_b": "Qirg'iz", "option_c": "O'zbek", "option_d": "Turkman", "correct_answer": "C"},
        {"text_uz": "Badiiy adabiyotning asosiy funksiyasi?", "option_a": "Ma'lumot berish", "option_b": "Estetik ta'sir ko'rsatish va tarbiyalash", "option_c": "Ilmiy bilim berish", "option_d": "Rasmiy hujjat tuzish", "correct_answer": "B"},
        {"text_uz": "Pьesa qanday adabiy janr?", "option_a": "Epik", "option_b": "Lirik", "option_c": "Dramatik", "option_d": "Lirik-epik", "correct_answer": "C"},
        {"text_uz": "Roman qanday janr?", "option_a": "Lirik", "option_b": "Dramatik", "option_c": "Katta epik", "option_d": "Kichik epik", "correct_answer": "C"},
        {"text_uz": "Hikoya qanday janr?", "option_a": "Katta epik", "option_b": "Lirik", "option_c": "Kichik proza janri", "option_d": "Dramatik", "correct_answer": "C"},
        {"text_uz": "Navoiyning tug'ilgan yili?", "option_a": "1441", "option_b": "1451", "option_c": "1461", "option_d": "1471", "correct_answer": "A"},
        {"text_uz": "Babur kim edi?", "option_a": "Shoir va sarkarda", "option_b": "Faqat sarkarda", "option_c": "Faqat shoir", "option_d": "Olim", "correct_answer": "A"},
        {"text_uz": "'Devoni Hикmat' asarini kim yozgan?", "option_a": "Navoiy", "option_b": "Ahmad Yassaviy", "option_c": "Bedil", "option_d": "Fuzuliy", "correct_answer": "B"},
        {"text_uz": "Mubolag'a — bu nima?", "option_a": "O'xshatish", "option_b": "Kuchaytirish, bo'rttirib ko'rsatish", "option_c": "Kamaytirib ko'rsatish", "option_d": "Sifatlash", "correct_answer": "B"},
        {"text_uz": "Tashbeh (o'xshatish) nima?", "option_a": "Ko'chma ma'no", "option_b": "Bir narsa yoki hodisani boshqasiga o'xshatish", "option_c": "Qarama-qarshilik", "option_d": "Takror", "correct_answer": "B"},
        {"text_uz": "Irony (kinoya) nima?", "option_a": "To'g'ridan-to'g'ri maqtov", "option_b": "Istehzoli, yashirin tanbeh", "option_c": "Mubolag'a", "option_d": "Tashbeh", "correct_answer": "B"},
    ],

    8: [  # Geografiya — 30 ta
        {"text_uz": "O'zbekistonning poytaxti?", "option_a": "Samarqand", "option_b": "Buxoro", "option_c": "Toshkent", "option_d": "Andijon", "correct_answer": "C"},
        {"text_uz": "Qaysi daryo O'zbekiston hududidan o'tadi?", "option_a": "Volga", "option_b": "Amudaryo", "option_c": "Don", "option_d": "Kama", "correct_answer": "B"},
        {"text_uz": "Orol dengiziga quyiladigan daryolar?", "option_a": "Sirdaryo va Amudaryo", "option_b": "Zarafshon va Qashqadaryo", "option_c": "Volga va Don", "option_d": "Nil va Kongo", "correct_answer": "A"},
        {"text_uz": "Dunyo bo'yicha eng katta kontinent?", "option_a": "Afrika", "option_b": "Amerika", "option_c": "Yevropa", "option_d": "Osiyo", "correct_answer": "D"},
        {"text_uz": "Dunyo bo'yicha eng uzun daryo?", "option_a": "Amazonka", "option_b": "Nil", "option_c": "Yantszi", "option_d": "Mississippi", "correct_answer": "B"},
        {"text_uz": "Yerning eng baland nuqtasi?", "option_a": "K2", "option_b": "Kanchenjunga", "option_c": "Everest (Chomolungma)", "option_d": "Lxotze", "correct_answer": "C"},
        {"text_uz": "Dunyo okeanlarining soni?", "option_a": "3", "option_b": "4", "option_c": "5", "option_d": "6", "correct_answer": "C"},
        {"text_uz": "Eng katta okean?", "option_a": "Atlantika", "option_b": "Hind", "option_c": "Shimoliy Muz", "option_d": "Tinch", "correct_answer": "D"},
        {"text_uz": "O'zbekistonda nechta viloyat bor?", "option_a": "11", "option_b": "12", "option_c": "13", "option_d": "14", "correct_answer": "C"},
        {"text_uz": "Sahara cho'li qaysi qit'ada?", "option_a": "Osiyo", "option_b": "Afrika", "option_c": "Avstraliya", "option_d": "Amerika", "correct_answer": "B"},
        {"text_uz": "Amazon daryo havzasi qaysi qit'ada?", "option_a": "Afrika", "option_b": "Osiyo", "option_c": "Janubiy Amerika", "option_d": "Shimoliy Amerika", "correct_answer": "C"},
        {"text_uz": "Dunyo bo'yicha eng ko'p aholiga ega davlat?", "option_a": "Hindiston", "option_b": "Xitoy", "option_c": "AQSH", "option_d": "Rossiya", "correct_answer": "A"},
        {"text_uz": "Yerning o'qi atrofida to'liq aylanish muddati?", "option_a": "12 soat", "option_b": "24 soat", "option_c": "365 kun", "option_d": "30 kun", "correct_answer": "B"},
        {"text_uz": "Yer Quyosh atrofida to'liq aylanish muddati?", "option_a": "24 soat", "option_b": "30 kun", "option_c": "365 kun 6 soat", "option_d": "100 yil", "correct_answer": "C"},
        {"text_uz": "Ekvator qayerda o'tadi?", "option_a": "Shimoliy qutbda", "option_b": "Janubiy qutbda", "option_c": "Yerning o'rta qismida", "option_d": "Tropiklar bo'ylab", "correct_answer": "C"},
        {"text_uz": "Toshkent necha metr balandlikda joylashgan (dengiz sathidan)?", "option_a": "200-300 m", "option_b": "400-500 m", "option_c": "600-700 m", "option_d": "800-1000 m", "correct_answer": "B"},
        {"text_uz": "Qaysi davlat dunyodagi eng katta maydonga ega?", "option_a": "Xitoy", "option_b": "AQSH", "option_c": "Kanada", "option_d": "Rossiya", "correct_answer": "D"},
        {"text_uz": "O'rta dengiz qaysi qit'alar orasida joylashgan?", "option_a": "Osiyo va Amerika", "option_b": "Yevropa, Afrika va Osiyo", "option_c": "Afrika va Avstraliya", "option_d": "Yevropa va Amerika", "correct_answer": "B"},
        {"text_uz": "Kaspiy dengizi aslida nima?", "option_a": "Dengiz", "option_b": "Ko'l", "option_c": "Bo'g'oz", "option_d": "Daryo", "correct_answer": "B"},
        {"text_uz": "Dunyo bo'yicha eng chuqur ko'l?", "option_a": "Kaspiy", "option_b": "Viktoriya", "option_c": "Baykal", "option_d": "Orol", "correct_answer": "C"},
        {"text_uz": "Tog' tizmalari orasida eng uzuni?", "option_a": "Himoloy", "option_b": "And tog'lari", "option_c": "Olp", "option_d": "Kavkaz", "correct_answer": "B"},
        {"text_uz": "O'zbekiston qaysi iqlim zonasida joylashgan?", "option_a": "Mo''tadil", "option_b": "Subtropik", "option_c": "Kontinental (quruq)", "option_d": "Arktik", "correct_answer": "C"},
        {"text_uz": "Sirdaryo qayerga quyiladi?", "option_a": "Kaspiy dengiziga", "option_b": "Orol dengiziga", "option_c": "Qora dengizga", "option_d": "Hind okeaniga", "correct_answer": "B"},
        {"text_uz": "O'zbekistonning qaysi qo'shnisi bilan eng uzun chegarasi bor?", "option_a": "Tojikiston", "option_b": "Qozog'iston", "option_c": "Afg'oniston", "option_d": "Turkmaniston", "correct_answer": "B"},
        {"text_uz": "Dunyo xaritasida geografik kenglik nima?", "option_a": "Ekvatordan janub yoki shimolga masofa", "option_b": "Grinvichdan sharq yoki g'arbga masofa", "option_c": "Dengiz sathidan balandlik", "option_d": "Ikki nuqta orasidagi masofa", "correct_answer": "A"},
        {"text_uz": "Geografik uzunlik nima?", "option_a": "Ekvatordan masofa", "option_b": "Grinvich meridianidan sharq yoki g'arbga masofa", "option_c": "Balandlik", "option_d": "Chuqurlik", "correct_answer": "B"},
        {"text_uz": "Ferghona vodiysi qaysi tog'lar bilan o'ralgan?", "option_a": "Tyanshan va Pomir", "option_b": "Qoraqum va Qizilqum", "option_c": "Oltoy va Ural", "option_d": "Kavkaz va Himoloy", "correct_answer": "A"},
        {"text_uz": "O'zbekistonda eng baland tog' cho'qqisi?", "option_a": "Chimyon", "option_b": "Xazratisulton", "option_c": "Muztog'ota", "option_d": "Beshtor", "correct_answer": "B"},
        {"text_uz": "Qizilqum cho'li qayerda joylashgan?", "option_a": "Faqat Turkmanistonda", "option_b": "O'zbekiston va Qozog'iston hududida", "option_c": "Faqat O'zbekistonda", "option_d": "Tojikiston va O'zbekistonda", "correct_answer": "B"},
        {"text_uz": "Zarafshon daryosi qayerdan boshlanadi?", "option_a": "Toshkent viloyatida", "option_b": "Qirg'izistonda", "option_c": "Tojikistonda", "option_d": "Afg'onistonda", "correct_answer": "C"},
    ],

    9: [  # Ingliz tili — 30 ta
        {"text_uz": "'Kitob' so'zining inglizchasi?", "option_a": "Book", "option_b": "Pen", "option_c": "Table", "option_d": "Chair", "correct_answer": "A"},
        {"text_uz": "What is your name? — ...", "option_a": "I am fine", "option_b": "My name is...", "option_c": "I am 20", "option_d": "I live here", "correct_answer": "B"},
        {"text_uz": "To be (Present Simple, I) = ?", "option_a": "is", "option_b": "are", "option_c": "am", "option_d": "was", "correct_answer": "C"},
        {"text_uz": "She ___ a student. (to be)", "option_a": "am", "option_b": "are", "option_c": "is", "option_d": "be", "correct_answer": "C"},
        {"text_uz": "They ___ happy. (to be)", "option_a": "am", "option_b": "is", "option_c": "are", "option_d": "was", "correct_answer": "C"},
        {"text_uz": "Past Simple of 'go'?", "option_a": "goed", "option_b": "gone", "option_c": "went", "option_d": "going", "correct_answer": "C"},
        {"text_uz": "Past Simple of 'eat'?", "option_a": "eated", "option_b": "eaten", "option_c": "ate", "option_d": "eating", "correct_answer": "C"},
        {"text_uz": "'Very big' = ?", "option_a": "Small", "option_b": "Huge/Enormous", "option_c": "Medium", "option_d": "Tiny", "correct_answer": "B"},
        {"text_uz": "Opposite of 'hot'?", "option_a": "Warm", "option_b": "Cool", "option_c": "Cold", "option_d": "Chilly", "correct_answer": "C"},
        {"text_uz": "How ___ apples are there?", "option_a": "much", "option_b": "many", "option_c": "some", "option_d": "any", "correct_answer": "B"},
        {"text_uz": "How ___ water is there?", "option_a": "many", "option_b": "much", "option_c": "some", "option_d": "few", "correct_answer": "B"},
        {"text_uz": "I ___ breakfast every morning. (have)", "option_a": "has", "option_b": "had", "option_c": "have", "option_d": "having", "correct_answer": "C"},
        {"text_uz": "'Beautiful' antonimi?", "option_a": "Pretty", "option_b": "Ugly", "option_c": "Nice", "option_d": "Gorgeous", "correct_answer": "B"},
        {"text_uz": "Present Continuous: She ___ now.", "option_a": "study", "option_b": "studies", "option_c": "is studying", "option_d": "studied", "correct_answer": "C"},
        {"text_uz": "Future Simple: I ___ go tomorrow.", "option_a": "shall", "option_b": "will", "option_c": "would", "option_d": "should", "correct_answer": "B"},
        {"text_uz": "'Fast' sinomimi?", "option_a": "Slow", "option_b": "Quick", "option_c": "Careful", "option_d": "Heavy", "correct_answer": "B"},
        {"text_uz": "Article 'an' qachon ishlatiladi?", "option_a": "Undosh bilan boshlangan so'z oldida", "option_b": "Unli bilan boshlangan so'z oldida", "option_c": "Ko'plik otlar oldida", "option_d": "Hech qachon", "correct_answer": "B"},
        {"text_uz": "'He doesn't ___ tennis.' (play)", "option_a": "plays", "option_b": "played", "option_c": "play", "option_d": "playing", "correct_answer": "C"},
        {"text_uz": "Present Perfect: She ___ the book. (read)", "option_a": "read", "option_b": "has read", "option_c": "have read", "option_d": "reads", "correct_answer": "B"},
        {"text_uz": "Comparative of 'good'?", "option_a": "gooder", "option_b": "more good", "option_c": "better", "option_d": "best", "correct_answer": "C"},
        {"text_uz": "Superlative of 'bad'?", "option_a": "baddest", "option_b": "most bad", "option_c": "worst", "option_d": "worse", "correct_answer": "C"},
        {"text_uz": "Passive voice: The book ___ by students.", "option_a": "reads", "option_b": "is read", "option_c": "reading", "option_d": "read", "correct_answer": "B"},
        {"text_uz": "Preposition: I am interested ___ music.", "option_a": "at", "option_b": "on", "option_c": "in", "option_d": "of", "correct_answer": "C"},
        {"text_uz": "Modal: You ___ wear a seatbelt. (obligation)", "option_a": "can", "option_b": "must", "option_c": "may", "option_d": "might", "correct_answer": "B"},
        {"text_uz": "Conditional: If it rains, I ___ stay home.", "option_a": "will", "option_b": "would", "option_c": "should", "option_d": "shall", "correct_answer": "A"},
        {"text_uz": "Indirect speech: He said he ___ tired.", "option_a": "is", "option_b": "was", "option_c": "are", "option_d": "were", "correct_answer": "B"},
        {"text_uz": "'I agree' = O'zbekchasi?", "option_a": "Men rad etaman", "option_b": "Men rozi emasman", "option_c": "Men roziman", "option_d": "Men tushunmadim", "correct_answer": "C"},
        {"text_uz": "Gerund: I enjoy ___. (swim)", "option_a": "swim", "option_b": "to swim", "option_c": "swimming", "option_d": "swam", "correct_answer": "C"},
        {"text_uz": "Infinitive: I want ___ English. (learn)", "option_a": "learn", "option_b": "learning", "option_c": "to learn", "option_d": "learned", "correct_answer": "C"},
        {"text_uz": "'However' qanday bog'lovchi?", "option_a": "Sabab", "option_b": "Natija", "option_c": "Qarama-qarshilik", "option_d": "Qo'shimcha", "correct_answer": "C"},
    ],

    10: [  # Rus tili — 30 ta
        {"text_uz": "'Kitob' so'zining ruschasi?", "option_a": "Книга", "option_b": "Ручка", "option_c": "Стол", "option_d": "Стул", "correct_answer": "A"},
        {"text_uz": "Как вас зовут? — ...", "option_a": "Мне хорошо", "option_b": "Меня зовут...", "option_c": "Мне 20 лет", "option_d": "Я живу здесь", "correct_answer": "B"},
        {"text_uz": "Rus tilida nechta grammatik jins bor?", "option_a": "2", "option_b": "3", "option_c": "4", "option_d": "5", "correct_answer": "B"},
        {"text_uz": "Мужской род — misol?", "option_a": "Книга", "option_b": "Окно", "option_c": "Стол", "option_d": "Дверь", "correct_answer": "C"},
        {"text_uz": "Женский род — misol?", "option_a": "Стол", "option_b": "Окно", "option_c": "Стул", "option_d": "Книга", "correct_answer": "D"},
        {"text_uz": "Средний род — misol?", "option_a": "Стол", "option_b": "Книга", "option_c": "Окно", "option_d": "Стул", "correct_answer": "C"},
        {"text_uz": "Rus tilida nechta kelishik bor?", "option_a": "4", "option_b": "5", "option_c": "6", "option_d": "7", "correct_answer": "C"},
        {"text_uz": "Я иду ___ школу. (qaysi predlog?)", "option_a": "в", "option_b": "на", "option_c": "к", "option_d": "от", "correct_answer": "A"},
        {"text_uz": "'Хорошо' antonimi?", "option_a": "Отлично", "option_b": "Плохо", "option_c": "Нормально", "option_d": "Средне", "correct_answer": "B"},
        {"text_uz": "Present tense: Я ___ (читать).", "option_a": "читает", "option_b": "читаешь", "option_c": "читаю", "option_d": "читают", "correct_answer": "C"},
        {"text_uz": "Present tense: Он ___ (читать).", "option_a": "читаю", "option_b": "читает", "option_c": "читаешь", "option_d": "читаем", "correct_answer": "B"},
        {"text_uz": "Числительное — bu qaysi so'z turkumi?", "option_a": "Fe'l", "option_b": "Ot", "option_c": "Son", "option_d": "Ravish", "correct_answer": "C"},
        {"text_uz": "'Большой' antonimi?", "option_a": "Огромный", "option_b": "Средний", "option_c": "Маленький", "option_d": "Широкий", "correct_answer": "C"},
        {"text_uz": "Past tense: Он ___ (идти).", "option_a": "идёт", "option_b": "шёл", "option_c": "пойдёт", "option_d": "ходит", "correct_answer": "B"},
        {"text_uz": "Future tense: Я ___ (читать).", "option_a": "читаю", "option_b": "читал", "option_c": "буду читать", "option_d": "читает", "correct_answer": "C"},
        {"text_uz": "Прилагательное 'красивый' qaysi so'z turkumi?", "option_a": "Ot", "option_b": "Fe'l", "option_c": "Sifat", "option_d": "Ravish", "correct_answer": "C"},
        {"text_uz": "Наречие 'быстро' qaysi so'z turkumi?", "option_a": "Sifat", "option_b": "Fe'l", "option_c": "Ravish", "option_d": "Ot", "correct_answer": "C"},
        {"text_uz": "'Писать' fe'lining buyruq shakli (sen)?", "option_a": "Пишу", "option_b": "Пишет", "option_c": "Пиши", "option_d": "Пишите", "correct_answer": "C"},
        {"text_uz": "Rus tilida urg'u nechta bo'lishi mumkin (bir so'zda)?", "option_a": "Faqat 1", "option_b": "2", "option_c": "3", "option_d": "Har qanday", "correct_answer": "A"},
        {"text_uz": "Мне нравится ___ (музыка). Qaysi kelishik?", "option_a": "Именительный", "option_b": "Родительный", "option_c": "Дательный", "option_d": "Винительный", "correct_answer": "A"},
        {"text_uz": "'Хотеть' fe'li qaysi spryajeniyaga kiradi?", "option_a": "I", "option_b": "II", "option_c": "Raznosprягaemoe", "option_d": "Irregular", "correct_answer": "C"},
        {"text_uz": "Совершенный вид fe'li nimani bildiradi?", "option_a": "Tugallanmagan harakat", "option_b": "Tugallangan harakat", "option_c": "Doimiy harakat", "option_d": "Takroriy harakat", "correct_answer": "B"},
        {"text_uz": "Несовершенный вид fe'li nimani bildiradi?", "option_a": "Tugallangan harakat", "option_b": "Tugallanmagan harakat", "option_c": "Bir martalik harakat", "option_d": "O'tgan harakat", "correct_answer": "B"},
        {"text_uz": "Мягкий знак (ь) qanday rol o'ynaydi?", "option_a": "Unli tovush", "option_b": "Undosh tovushni yumshatadi", "option_c": "Urg'u belgisi", "option_d": "Ajratish belgisi", "correct_answer": "B"},
        {"text_uz": "Твёрдый знак (ъ) qachon ishlatiladi?", "option_a": "So'z oxirida", "option_b": "Prefiks va ildiz orasida ajratish uchun", "option_c": "Undoshdan keyin", "option_d": "Unlidan oldin", "correct_answer": "B"},
        {"text_uz": "'Красиво' qaysi so'z turkumi?", "option_a": "Sifat", "option_b": "Ot", "option_c": "Ravish", "option_d": "Fe'l", "correct_answer": "C"},
        {"text_uz": "Деепричастие nima?", "option_a": "Sifatdosh", "option_b": "Ravishdosh", "option_c": "Fe'l", "option_d": "Ot", "correct_answer": "B"},
        {"text_uz": "Причастие nima?", "option_a": "Sifatdosh", "option_b": "Ravishdosh", "option_c": "Ravish", "option_d": "Olmosh", "correct_answer": "A"},
        {"text_uz": "Я иду ___ магазина. (qaysi predlog — chiqish ma'nosi)", "option_a": "в", "option_b": "к", "option_c": "из", "option_d": "на", "correct_answer": "C"},
        {"text_uz": "Rus tilida undosh harflar soni?", "option_a": "20", "option_b": "21", "option_c": "22", "option_d": "23", "correct_answer": "B"},
    ],
}


def seed_questions():
    """Seed questions — har bir fanda 30 ta, jami 300 ta"""
    db = Session()
    try:
        existing = db.query(Question).count()
        if existing >= 300:
            print(f"Savollar allaqachon bor: {existing} ta. O'tkazib yuborildi.")
            return

        total = 0
        for subject_id, questions in QUESTIONS_DATA.items():
            subject = db.query(Subject).filter(Subject.id == subject_id).first()
            if not subject:
                print(f"❌ Fan {subject_id} topilmadi — o'tkazib yuborildi")
                continue

            for q_data in questions:
                question = Question(
                    subject_id=subject_id,
                    text_uz=q_data["text_uz"],
                    text_oz=q_data.get("text_oz", q_data["text_uz"]),
                    text_ru=q_data.get("text_ru", q_data["text_uz"]),
                    option_a=q_data["option_a"],
                    option_b=q_data["option_b"],
                    option_c=q_data["option_c"],
                    option_d=q_data["option_d"],
                    correct_answer=q_data["correct_answer"],
                    difficulty=random.choice(["easy", "medium", "hard"]),
                )
                db.add(question)
                total += 1

        db.commit()
        print(f"✅ {total} ta savol qo'shildi!")

        for subject in db.query(Subject).all():
            count = db.query(Question).filter(Question.subject_id == subject.id).count()
            subject.question_count = count
        db.commit()
        print("✅ Fanlarning savol sonlari yangilandi!")

    except Exception as e:
        db.rollback()
        print(f"❌ Xato: {e}")
    finally:
        db.close()


if __name__ == "__main__":
    print("📚 DTM Test Bot — savollarni qo'shish...")
    init_db()
    seed_questions()
    print("🎉 Tayyor!")